### PR TITLE
Add conversion methods to DCM

### PR DESCRIPTION
**Pull request by juliohm**
Related to #18 

This PR is a first step towards solving the manual conversion between different rotation types. After reading the code more carefully I realized that we will need to refactor existing types before we can add more conversion methods. I will open specific issues to discuss this further.

Appreciate if you can review this PR before I can continue working in other improvements.

### CODE REVIEW

**Comment by ronisbr** [comment]
Any idea why the tests are failing against nightly?

**Comment by juliohm** [comment]
Hi @ronisbr the errors on nightly seem unrelated to the changes in the PR. Can you please double check and see if everything is ok to merge?

**Comment by ronisbr** [comment]
Hi @juliohm 

I will investigate because it seems that `master` is passing here without problems.

**Comment by ronisbr** [comment]
Hi @juliohm 

Sorry for the late response. Yes, the errors does not seem to be related to this PR, but with something that has changed with Julia-nightly.

**Comment by ronisbr** [comment]
I also added the conversion to quaternions. The problem with Euler Angles and Euler Angle and Axis is that the type by itself does not fully define the representation. Hence, I am not sure how to implement the Julia conversion API for them.

**Comment by juliohm** [comment]
Yes it would be nice to refactor these types so that they are self
contained somehow at compile time. The symbol :ZXZ for example could be a
type parameter.

**Comment by ronisbr** [comment]
Yes, this will solve for Euler angles. However, for Euler angle and axis I have no idea :D

**Comment by juliohm** [comment]
Can every rotation be converted to an angle axis? I thought that this was a
subset of all possible rotations. In that case it would make sense to
figure out which representations could be naturally converted into angle
axis. Maybe we don't need conversion methods for this one.

**Comment by ronisbr** [comment]
Yes, you can always convert a rotation to an Euler angle and axis. However, the axis direction is not constant. For every DCM, for example, there is a different rotation axis.

**Pull request merged**
