### PR TITLE
Use Travis' Julia / Codecov / Coveralls support

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by fingolfin** [comment]
It seems you disabled Travis for pull requests, so this won't get tested :-(

**Comment by fingolfin** [comment]
Uhh, OK... now I just hope it doesn't break... Any particular reason you don't want PRs to be tested? To me, that's one of the primary benefits of using a service like Travis.

**Comment by ronisbr** [comment]
No, actually, I am not sure why I disabled it. It is enabled now.

**Comment by fingolfin** [comment]
(Oh, and of course the Julia 1.0 and 1.1 builds will fail anyway, due to https://github.com/JuliaWeb/MbedTLS.jl/issues/193

**Comment by ronisbr** [comment]
Yeah, I just saw this :) However, your patch seems to be working OK, since the process to submit to Coverage and Coveralls was executed.

**Comment by fingolfin** [comment]
yeah, phew, that's a relief :) I am rather heavily depending on Travis double checking my PRs these days :)

**Pull request merged**
